In [2]:
import numpy as np

In [3]:
array = [1,2,3]

In [4]:
array = np.array(array)

In [5]:
array

array([1, 2, 3])

In [6]:
type(array)

numpy.ndarray

In [8]:
#multi dimensional array
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
arr3 = [11,12,13,14,15]
fin_arr = np.array([arr1,arr2,arr3])
fin_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
fin_arr.shape

(3, 5)

In [9]:
fin_arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [10]:
#multidimensional array
a1 = [5,4,3,2,1]
a2 = [10,9,8,7,6]
a3 = [15,14,13,12,11]

In [12]:
f = np.array([a1,a2,a3])

In [13]:
f

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [14]:
f.shape

(3, 5)

In [16]:
f.resize(1,15)
f

array([[ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6, 15, 14, 13, 12, 11]])

In [17]:
f

array([[ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6, 15, 14, 13, 12, 11]])

In [18]:
f = np.array([a1,a2,a3])
f

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [20]:
g = np.array([[1,2,3],[4,5,6]])
g

array([[1, 2, 3],
       [4, 5, 6]])

**indexing**

In [21]:
g[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(g[0:1,0:2])#prints row 0 and column from o to 1

[[1 2]]


In [10]:
h = np.arange(0,10,dtype = float)
h

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
print(h[3:])

[3. 4. 5. 6. 7. 8. 9.]


In [13]:
m=np.linspace(0,10,36)
m

array([ 0.        ,  0.28571429,  0.57142857,  0.85714286,  1.14285714,
        1.42857143,  1.71428571,  2.        ,  2.28571429,  2.57142857,
        2.85714286,  3.14285714,  3.42857143,  3.71428571,  4.        ,
        4.28571429,  4.57142857,  4.85714286,  5.14285714,  5.42857143,
        5.71428571,  6.        ,  6.28571429,  6.57142857,  6.85714286,
        7.14285714,  7.42857143,  7.71428571,  8.        ,  8.28571429,
        8.57142857,  8.85714286,  9.14285714,  9.42857143,  9.71428571,
       10.        ])

**concept of referencing and why copy function is necessary**

In [14]:
#create an np array
old_array = np.array([1,2,3,4])
#create a new array and it must be assigned to old_array
new_array = old_array
#now change value of new array
new_array[2:] = 100
#check values of new and old array
new_array
#in cpp, you can called at aliasing concept(function reference)

array([  1,   2, 100, 100])

In [15]:
old_array

array([  1,   2, 100, 100])

In [16]:
#normal one:
x = 20
y =x
y = 30
print(x,y)

20 30


**we need concept of copy**

In [17]:
new_array = np.copy(old_array)

In [18]:
new_array[2:] = 300
print(new_array)
print(old_array)

[  1   2 300 300]
[  1   2 100 100]


In [20]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
z1 = np.ones((2,3),dtype = float)
z1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
z2 = np.random.rand(3,1)
z2

array([[0.88099807],
       [0.79536964],
       [0.44021492]])