In [5]:
import seaborn as sns

In [6]:
df = sns.load_dataset("tips")

In [7]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [55]:
import numpy as np

In [56]:
list = [1,2,3]
list1 = [4,5,6]
list2 = [7,8,9]

In [57]:
a1 = np.array([list,list1,list2])

In [58]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a1.shape

(3, 3)

In [60]:
a1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
a1.resize(3,3)

In [62]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
a1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [65]:
a2 = np.arange(0,9,dtype = float)

In [66]:
a2.reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [67]:
a3 = np.arange(0,10,dtype = float)

In [68]:
a3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
a3.resize(2,5)

In [77]:
a3

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])